# escape=`

ARG WINDOWS_TAG
FROM $WINDOWS_TAG

RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install `
    "Microsoft.PowerShell.Utility.Activities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
